const routes=[
  {path:'/',redirect:'/home'},
  {
    path:'/home',
    name:'home',
    component:()=>import('./view/home/index')
  },
  {
    path:'/blog',
    name:'blog',
    redirect:{name:'blogList'},
    component:()=>import("./view/blog/index"),
    children:[
      {
        path:'list',
        name:'blogList',
        component:()=>import('./view/blog/BlogList.vue')
      },
      {
        path:'view/:id',
        name:'blogView',
        props:true,
        component:()=>import('./view/blog/BlogDetail.vue')
      }
    ]
  },
  {
    path:'/shop',
    name:'shop',
    component:()=>import('./view/cart/index')
  },
  {
    path:'/answer',
    name:'answer',
    redirect:{name:'answerList'},
    component:()=>import("./view/answer/index"),
    children:[
      {
        path:'list',
        name:'answerList',
        component:()=>import('./view/answer/AnswerList.vue')
      },
      {
        path:'view/:id',
        name:'answerView',
        props:true,
        component:()=>import('./view/answer/AnswerDetail.vue')
      }
    ]
  },
  {
    path:'/baidu',
    name:'baidu',
    component:()=>import('./view/baidu/baidu.vue')
  }
]

export default routes;